version: '3.7'

services:
  site_kit_sync:
    container_name: site_kit_sync
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - site_kit_sync_db
    links:
      - site_kit_sync_db
    volumes:
      - .:/usr/app

  # PostgreSQL service
  site_kit_sync_db:
    container_name: site_kit_sync_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'

  site_kit_sync_test_db:
    container_name: site_kit_sync_test_db
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: site_kit_sync_test_db
    ports:
      - '5434:5432'
